config/routes.rb
Rails.application.routes.draw do

  root 'admin/dashboard#index'

  devise_for :users,
    controllers: {
      passwords:   'users/passwords',
      sessions:    'users/sessions',
      invitations: 'users/creations'
    },
    path_names: {
      invitation: 'creation'
    },
    skip: [:registrations, :confirmations]

  devise_scope :user do
    # 超級管理員註冊
    get  'super_admin/sign_up', to: 'super_admin/registrations#new'
    post 'super_admin/sign_up', to: 'super_admin/registrations#create'
    # 重發超級管理員認證信
    get  'super_admin/confirmation/resend', to: 'super_admin/confirmations#new'
    get  'super_admin/confirmation',        to: 'super_admin/confirmations#show'
    post 'super_admin/confirmation',        to: 'super_admin/confirmations#create'
    # 變更密碼
    get  'admin/users/edit', to: 'users/registrations#edit',   as: 'edit_user_registration'
    put  'admin/users',      to: 'users/registrations#update', as: 'user_registration'
    # 新增人員
    get  'admin/users/creation/new', to: 'users/creations#new',    as: 'admin_users_creation_new'
    post 'admin/users/creation',     to: 'users/creations#create', as: 'admin_users_creation'
  end

  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update] do
      member do
        # 重寄新增認證信
        get    'creation/resend', to: 'users#resend_creation'
        # 鎖定與解鎖帳號
        delete 'lock',   to: 'users#lock'
        put    'unlock', to: 'users#unlock'
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  include UserProfileable

  # Include default devise modules. Others available are:
  # :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :timeoutable, :invitable, :lockable

  # 使用者登入紀錄
  def after_database_authentication
    Log.write(self, self, 'user_sign_in')
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController

  load_and_authorize_resource

  def index
    @users = @users.includes(:profile)
  end

  def show
  end

  def edit
    @user.build_profile if @user.profile.nil?
  end

  def update
    if @user.update(user_params)
      # 紀錄更新人員事件
      Log.write(current_user, @user, 'update_user')
      redirect_to admin_user_url(@user), notice: t('user.messages.edit_success', email: @user.email)
    else
      render :edit
    end
  end

  def resend_creation
    @user.invite!
    # 紀錄重寄認證信事件
    Log.write(current_user, @user, 'resend_creation')
    redirect_to admin_user_url(@user), notice: t('user.messages.resend_creation_success', email: @user.email)
  end

  def lock
    if @user.lock_access!(send_instructions: false)
      # 紀錄鎖定人員事件
      Log.write(current_user, @user, 'lock_user')
      redirect_to admin_user_url(@user), notice: t('user.messages.lock_success', email: @user.email)
    end
  end

  def unlock
    if @user.unlock_access!
      # 紀錄解鎖人員事件
      Log.write(current_user, @user, 'unlock_user')
      redirect_to admin_user_url(@user), notice: t('user.messages.unlock_success', email: @user.email)
    end
  end

  private

    def user_params
      params.require(:user).permit(profile_attributes: [:id, :role])
    end
end

app/controllers/users/creations_controller.rb
class Users::CreationsController < Devise::InvitationsController

  before_action :configure_permitted_parameters, if: :devise_controller?

  def new
    # CanCanCan
    authorize! :create, User

    self.resource = resource_class.new
    self.resource.build_profile if self.resource.profile.nil?

    render :new
  end

  def create
    # CanCanCan
    authorize! :create, User

    super do |resource|
      # 紀錄新增人員事件
      Log.write(current_user, resource, 'create_user') if resource.errors.empty?
    end
  end

  def update
    super do |resource|
      # 紀錄接受新增事件
      Log.write(resource, resource.invited_by, 'accept_creation') if resource.errors.empty?
    end
  end

  def after_invite_path_for(resource)
    admin_users_url
  end

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:invite, keys: [
        { profile_attributes: [:id, :role] }
      ])
    end

    def translation_scope
      'devise.creations'
    end
end

app/controllers/users/invitations_controller.rb
class Users::InvitationsController < Devise::InvitationsController

  before_action :configure_permitted_parameters, if: :devise_controller?

  def new
    # CanCanCan
    authorize! :invite, User

    self.resource = resource_class.new
    self.resource.build_profile if self.resource.profile.nil?

    render :new
  end

  def create
    # CanCanCan
    authorize! :invite, User

    super do |resource|
      # 紀錄邀請會員事件
      Log.write(current_user, resource, 'invited_user') if resource.errors.empty?
    end
  end

  def update
    super do |resource|
      # 紀錄會員接受邀請事件
      Log.write(resource, resource.invited_by, 'accepted_invitation') if resource.errors.empty?
    end
  end

  def after_invite_path_for(resource)
    admin_users_url
  end

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:invite, keys: [
        { profile_attributes: [:id, :role] }
      ])
    end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController

  def update
    super do |resource|
      # 紀錄使用者修改密碼事件
      Log.write(resource, resource, 'reset_password') if resource.errors.empty?
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  before_action :configure_permitted_parameters, if: :devise_controller?

  def edit
    resource.build_profile if resource.profile.nil?
  end

  def update
    super do |resource|
      # 紀錄使用者修改密碼事件
      Log.write(resource, resource, 'change_password') if resource.errors.empty?
    end
  end

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:account_update, keys: [
        { profile_attributes: [:id, :name] }
      ])
    end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

  def new
    # # 當無任何超級管理員時，則跳轉到超級管理員註冊頁面
    redirect_to super_admin_sign_up_url and return if User.super_admin.blank?
    # 載入上次登入的 Email 資訊
    if cookies[:email].present?
      params[:user] = { email: cookies[:email] }
      params[:remember_me] = '1'
    end
    super
  end

  def create
    super do |resource|
      # 儲存此次登入的 Email 資訊
      # 儲存此次登入的 Email 資訊
      if params[:remember_me] == '1'
        cookies.permanent[:email] = { value: params[:user][:email], httponly: true }
      else
        cookies.delete(:email)
      end
    end
  end

  protected

    def after_sign_out_path_for(resource_or_scope)
      new_user_session_url
    end
end

app/views/admin/users/edit.html.haml
- content_for :title, t('user.labels.management')

.row
  .col-md-12.col-sm-12.col-xs-12
    .x_panel
      .x_title
        %h2= t('user.titles.edit')
        %ul.nav.navbar-right.panel_toolbox
          %li
            %a.collapse-link= fa_icon('chevron-up')
        .clearfix
      .x_content
        = simple_form_for @user, url: admin_user_url, html: { class: 'form-horizontal' }, wrapper: :horizontal_form do |f|
          = f.input :email, input_wrapper_html: { class: 'col-sm-9' } do
            %p.form-control-static
              = @user.email
          = f.fields_for :profile, wrapper: :horizontal_form do |p|
            = p.input :role, collection: Profile.role_select_options, input_wrapper_html: { class: 'col-sm-3' }
          .ln_solid
          .form-group
            .col-sm-6.col-xs-12.col-md-offset-3
              = f.button :submit, t('common.labels.submit'), class: 'btn-success'
              = link_to t('common.labels.cancel'), admin_user_url(@user), class: 'btn btn-default'

app/views/admin/users/index.html.haml
- content_for :title, t('user.labels.management')

.row
  - if can? :create, User
    .col-md-12.col-sm-12.col-xs-12.toolbar
      .x_panel
        .x_title
          %h2= t('common.labels.toolbar')
          %ul.nav.navbar-right.panel_toolbox
            %li
              %a.collapse-link= fa_icon('chevron-up')
          .clearfix
        .x_content
          = link_to admin_users_creation_new_url, class: 'btn btn-app btn-sm' do
            = fa_icon('user-plus')
            = t('user.labels.create_user')
  .col-md-12.col-sm-12.col-xs-12
    .x_panel
      .x_title
        %h2= t('user.titles.index')
        %ul.nav.navbar-right.panel_toolbox
          %li
            %a.collapse-link= fa_icon('chevron-up')
        .clearfix
      .x_content
        %table.table.table-bordered.dt-responsive.nowrap
          %thead
            %tr
              %th= User.human_attribute_name(:email)
              %th= Profile.human_attribute_name(:name)
              %th= Profile.human_attribute_name(:role)
              %th= User.human_attribute_name(:sign_in_count)
              %th= User.human_attribute_name(:current_sign_in_at)
              %th
          %tbody
            - @users.each do |user|
              %tr
                %td= user.email
                %td= user.profile.name
                %td= Profile.human_attribute_name("role.#{user.profile.role}")
                %td= user.sign_in_count
                %td= user.current_sign_in_at
                %td
                  = link_to admin_user_url(user), class: 'btn btn-primary btn-xs' do
                    = fa_icon('folder')
                    = t('common.labels.view')

app/views/admin/users/show.html.haml
- content_for :title, t('user.labels.management')

.row
  .col-md-12.col-sm-12.col-xs-12.toolbar
    .x_panel
      .x_title
        %h2= t('common.labels.toolbar')
        %ul.nav.navbar-right.panel_toolbox
          %li
            %a.collapse-link= fa_icon('chevron-up')
        .clearfix
      .x_content
        = link_to admin_users_url, class: 'btn btn-app btn-sm' do
          = fa_icon('caret-square-o-left')
          = t('common.labels.back')
        - if can?(:resend_creation, @user)
          = link_to creation_resend_admin_user_url(@user), class: 'btn btn-app btn-sm', 'data-confirm' => t('common.messages.confirm') do
            = fa_icon('envelope-o')
            = t('user.labels.resend_creation')
        - if can?(:update, @user)
          = link_to edit_admin_user_url(@user), class: 'btn btn-app btn-sm' do
            = fa_icon('pencil')
            = t('common.labels.edit')
        - if can?(:lock, @user)
          = link_to lock_admin_user_url(@user), class: 'btn btn-app btn-sm', 'data-confirm' => t('common.messages.confirm'), method: 'delete' do
            = fa_icon('lock')
            = t('common.labels.lock')
        - if can?(:unlock, @user)
          = link_to unlock_admin_user_url(@user), class: 'btn btn-app btn-sm', 'data-confirm' => t('common.messages.confirm'), method: 'put' do
            = fa_icon('unlock')
            = t('common.labels.unlock')
  .col-md-12.col-sm-12.col-xs-12
    .x_panel
      .x_title
        %h2= t('user.titles.show')
        %ul.nav.navbar-right.panel_toolbox
          %li
            %a.collapse-link= fa_icon('chevron-up')
        .clearfix
      .x_content
        .form-horizontal
          .form-group
            = label_tag :user, User.human_attribute_name(:email), class: 'control-label col-sm-2 col-xs-12'
            .col-sm-10.col-xs-12
              %p.form-control-static
                = @user.email
          .form-group
            = label_tag :user, Profile.human_attribute_name(:name), class: 'control-label col-sm-2 col-xs-12'
            .col-sm-10.col-xs-12
              %p.form-control-static
                = @user.profile.name
          .form-group
            = label_tag :user, Profile.human_attribute_name(:role), class: 'control-label col-sm-2 col-xs-12'
            .col-sm-10.col-xs-12
              %p.form-control-static
                = Profile.human_attribute_name("role.#{@user.profile.role}")
          .form-group
            = label_tag :user, User.human_attribute_name(:sign_in_count), class: 'control-label col-sm-2 col-xs-12'
            .col-sm-10.col-xs-12
              %p.form-control-static
                = @user.sign_in_count
          .form-group
            = label_tag :user, User.human_attribute_name(:current_sign_in_at), class: 'control-label col-sm-2 col-xs-12'
            .col-sm-10.col-xs-12
              %p.form-control-static
                = @user.current_sign_in_at
          - if @user.created_by_invite?
            .form-group
              = label_tag :user, User.human_attribute_name(:invitation_created_at), class: 'control-label col-sm-2 col-xs-12'
              .col-sm-10.col-xs-12
                %p.form-control-static
                  = @user.invitation_created_at
            .form-group
              = label_tag :user, User.human_attribute_name(:invited_by), class: 'control-label col-sm-2 col-xs-12'
              .col-sm-10.col-xs-12
                %p.form-control-static
                  = @user.invited_by.email
            .form-group
              = label_tag :user, User.human_attribute_name(:locked_at), class: 'control-label col-sm-2 col-xs-12'
              .col-sm-10.col-xs-12
                %p.form-control-static
                  = @user.locked_at