config/routes.rb
Rails.application.routes.draw do

  root 'admin/dashboard#index'

  devise_for :users,
    controllers: {
      passwords:   'users/passwords',
      sessions:    'users/sessions',
      invitations: 'users/creations'
    },
    path_names: {
      invitation: 'creation'
    },
    skip: [:registrations, :confirmations]

  devise_scope :user do
    # 超級管理員註冊
    get  'super_admin/sign_up', to: 'super_admin/registrations#new'
    post 'super_admin/sign_up', to: 'super_admin/registrations#create'
    # 重發超級管理員認證信
    get  'super_admin/confirmation/resend', to: 'super_admin/confirmations#new'
    get  'super_admin/confirmation',        to: 'super_admin/confirmations#show'
    post 'super_admin/confirmation',        to: 'super_admin/confirmations#create'
    # 變更密碼
    get  'admin/users/edit', to: 'users/registrations#edit',   as: 'edit_user_registration'
    put  'admin/users',      to: 'users/registrations#update', as: 'user_registration'
    # 新增人員
    get  'admin/users/creation/new', to: 'users/creations#new',    as: 'admin_users_creation_new'
    post 'admin/users/creation',     to: 'users/creations#create', as: 'admin_users_creation'
  end

  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update] do
      member do
        # 重寄新增認證信
        get    'creation/resend', to: 'users#resend_creation'
        # 鎖定與解鎖帳號
        delete 'lock',   to: 'users#lock'
        put    'unlock', to: 'users#unlock'
      end
    end
  end
end

app/views/shared/components/_footer.html.haml
%footer
  .pull-right
    = "© #{Time.now.year} 益科股份有限公司 Ecowork Inc. 版權所有"
  .clearfix

app/views/shared/components/_nav_title.html.haml
.navbar.nav_title{ style: 'border:0' }
  = link_to root_url, class: 'site_title' do
    = fa_icon('mobile lg')
    %span PrivatePush
.clearfix

app/views/shared/components/_page_title.html.haml
.page-title
  .title_left
    %h3
      = yield :title
.clearfix

app/views/shared/components/_sidebar_menu.html.haml
#sidebar-menu.main_menu_side.hidden-print.main_menu
  .menu_section
    %ul.nav.side-menu

      - if can? :read, User
        = sidebar_menu_item controller: ['admin/users', 'users/invitations'] do
          = link_to '#' do
            = fa_icon('users')
            %label= t('user.labels.management')
            %span.fa.fa-chevron-down
          %ul.nav.child_menu
            = sidebar_child_menu_item controller: 'admin/users', action: :index do
              = link_to admin_users_url do
                = t('user.titles.index')

app/views/shared/components/_top_nav.html.haml
.top_nav
  .nav_menu
    %nav{ role: 'navigation' }
      .nav.toggle
        %a#menu_toggle
          %i.fa.fa-bars
      %ul.nav.navbar-nav.navbar-right
        %li
          %a.user-profile.dropdown-toggle{ 'aria-expanded' => 'false', 'data-toggle' => 'dropdown', href: 'javascript:;' }
            = current_user.name
            %span.fa.fa-angle-down
          %ul.dropdown-menu.dropdown-usermenu.pull-right
            %li
              = link_to edit_user_registration_url do
                = fa_icon('edit', class: 'pull-right')
                = t('user.labels.edit_profile')
            %li
              = link_to destroy_user_session_url, method: :delete do
                = fa_icon('sign-out', class: 'pull-right')
                = t('devise.labels.sign_out')